/***************************************************************************************************
 * FileName:             NativeEventHandler.cs
 * Date:                 20180922
 * Copyright:            Copyright © 2017-2018 Thomas Corwin, et al. All Rights Reserved.
 * License:              https://github.com/tacdevel/tcdfx/blob/master/LICENSE.md
 **************************************************************************************************/

namespace TCD
{
    /// <summary>
    /// Represents the method that will handle an event that has no event data.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    public delegate void NativeEventHandler(object sender);

    /// <summary>
    /// Represents the method that will handle an event that has no event data.
    /// </summary>
    /// <typeparam name="TSender">The type of sender object.</typeparam>
    /// <param name="sender">The source of the event.</param>
    public delegate void NativeEventHandler<TSender>(TSender sender);

    /// <summary>
    /// Represents the method that will handle an event when the event provides data.
    /// </summary>
    /// <typeparam name="TSender">The type of sender object.</typeparam>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    public delegate void NativeEventHandler<TSender, TEventArgs>(TSender sender, TEventArgs e);
}