/****************************************************************************
 * FileName:   EventHandlerEx.cs
 * Assembly:   TCD.Core.dll
 * Package:    TCD.Core
 * Date:       20180922
 * License:    MIT License
 * LicenseUrl: https://github.com/tacdevel/TDCFx/blob/master/LICENSE.md
 ***************************************************************************/

namespace TCD
{
    /// <summary>
    /// Represents the method that will handle an event that has no event data.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    public delegate void Event(object sender);

    /// <summary>
    /// Represents the method that will handle an event that has no event data.
    /// </summary>
    /// <typeparam name="TSender">The type of sender object.</typeparam>
    /// <param name="sender">The source of the event.</param>
    public delegate void Event<TSender>(TSender sender);

    /// <summary>
    /// Represents the method that will handle an event when the event provides data.
    /// </summary>
    /// <typeparam name="TSender">The type of sender object.</typeparam>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    public delegate void Event<TSender, TEventArgs>(TSender sender, TEventArgs e);
}