/***********************************************************************************************************************
 * FileName:             GenericEventHandler.cs
 * Copyright:            Copyright © 2017-2020 Thomas Corwin, et al. All Rights Reserved.
 * License:              https://github.com/tom-corwin/tacdevelfx/blob/master/LICENSE.md
 **********************************************************************************************************************/

using System;

namespace TACDevel
{
    /// <summary>
    /// Represents the method that will handle an event when the event provides data.
    /// </summary>
    /// <typeparam name="TSender">The type of sender object.</typeparam>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    public delegate void GenericEventHandler<TSender, TEventArgs>(TSender sender, TEventArgs e);
}