//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDFx.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCDFx.Core.resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space from &apos;{0}&apos; to the end of the destination &apos;{1}&apos; to copy the source array..
        /// </summary>
        internal static string ArrayPlusOffsetTooSmall {
            get {
                return ResourceManager.GetString("ArrayPlusOffsetTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid handle cannot be released..
        /// </summary>
        internal static string CannotReleaseInvalidHandle {
            get {
                return ResourceManager.GetString("CannotReleaseInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a non-negative, zero-based index..
        /// </summary>
        internal static string IndexMustBeNonNegative {
            get {
                return ResourceManager.GetString("IndexMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid type of array..
        /// </summary>
        internal static string InvalidArrayType {
            get {
                return ResourceManager.GetString("InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional arrays are not supported..
        /// </summary>
        internal static string MultiDimArrayNotSupported {
            get {
                return ResourceManager.GetString("MultiDimArrayNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find or load the native library using any name: [ {0} ].
        /// </summary>
        internal static string NativeAssemblyNotFound {
            get {
                return ResourceManager.GetString("NativeAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function was found with the name &apos;{0}&apos;..
        /// </summary>
        internal static string NativeFunctionNotFound {
            get {
                return ResourceManager.GetString("NativeFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be changed once it is set..
        /// </summary>
        internal static string ObjectIsImmutable {
            get {
                return ResourceManager.GetString("ObjectIsImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be null..
        /// </summary>
        internal static string ObjectMustNotBeNull {
            get {
                return ResourceManager.GetString("ObjectMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be null, empty, or whitespace..
        /// </summary>
        internal static string ObjectMustNotBeNullEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("ObjectMustNotBeNullEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be null or empty..
        /// </summary>
        internal static string ObjectMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ObjectMustNotBeNullOrEmpty", resourceCulture);
            }
        }
    }
}
